version: '3.1'
services:
  # other services

  mysql:
    container_name: flask_mysql
    restart: always
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1234abc'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
      MYSQL_DATABASE: 'books'
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: 'flask_mysql'
      DB_USER: 'root'
      DB_PWD: '1234abc'
      DB_NAME: 'books'
